public enum EDialogueTitle
{
    RutePerjalanan,
    PerhatianUmum,
    NyalakanMesin,
    PemeriksaanPreoperasional,
    AktivasiSistem,
    PembersihanPreoperasional,
    BersihkanPassChamber,
    BersihkanProcessChamber,
    BersihkanTimbangan,
    BersihkanViableAirSampler,
    BersihkanParticleCounter,
    BersihkanGloves,
    BersihkanMaterialTimbang,
    BersihkanPermukaanMesin,
    PressureDecayTest,
    MasterChamberLeakTest,
    PassChamberLeakTest
}